### ISSUE TITLE
Only one realization is stored

### ISSUE THREAD

**Issue by mariosgeo** [juliohm/ImageQuilting.jl#13]
Hi,

I am new to Julia so I might be wrong. I was using ImageQuilting for few days, but after today (some updates took place), the command 
    reals, cuts, voxs = iqsim(TI, 13, 13, 1, size(TI)..., nreal=3)

only returns one realization.

**Comment by mariosgeo** [comment]
I have a feeling that this is related to Compat.

**Comment by juliohm** [comment]
Hi @mariosgeo thank you for contacting. The outputs `cuts` and `voxs` are only returned if you pass in the option `debug=true`. Maybe that is causing the issue for you? I think what is happening is that you are requesting 3 realizations and then saving each of them in three variables `reals`, `cuts`, `voxs`.

Could you please add the option `debug=true` to see if the issue is solved? If you don't need these debug outputs, you can just write `reals = iqsim(TI, 13, 13, 1, size(TI)..., nreal=3)` and then `reals` becomes a vector with 3 realizations.

**Comment by mariosgeo** [comment]
Thanks for the fast response. It seems removing the cuts and voxs arguments
did the trick.


Thanks a lot

**Comment by juliohm** [comment]
Thank you @mariosgeo , if you have future questions, please reach out in our gitter channel: https://gitter.im/JuliaEarth/GeoStats.jl
